name: ProductRestaurant
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pdf: ^3.11.1
  printing: ^5.13.3
  shared_preferences: ^2.3.2
  date_time_picker: ^2.1.0
  flutter_typeahead: ^4.8.0

  http: any
  pinput: ^5.0.0
  lottie: ^3.1.2
  device_info_plus: ^10.1.2
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  dropdown_button2: ^2.3.9
  qr_flutter: ^4.1.0
  flutter_html: ^3.0.0-beta.2
  open_file: ^3.5.6
  permission_handler: ^11.3.1
  universal_html: ^2.2.4
  dotted_border: ^2.1.0
  scrollable: ^1.0.5
  syncfusion_flutter_charts: ^21.2.4
  # charts_flutter: ^0.12.0
  flutter_svg: ^2.0.10+1
  syncfusion_flutter_xlsio: ^21.2.3
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/json/order.json
    - assets/json/interaction.json
    - assets/json/delivery.json

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf

    - family: Source Sans 3
      fonts:
        - asset: assets/fonts/SourceSans3-SemiBold.ttf

    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-SemiBold.ttf

